/**
 * DocumentIcons - SVG icons for document types
 *
 * Provides icons for CSV, JSON, and other document formats.
 * Supports active state styling.
 *
 * Note: This is a Server Component that uses CSS variables for theme values.
 * CSS variables are generated by MUI's cssVariables mode in theme.tsx.
 */

import { Box } from "../.."
import type { SxProps, Theme } from "@mui/material/styles"

// CSS variable references for theme colors (from cssVariables mode)
const ACTIVE_COLOR = "var(--mui-palette-blue-bright)"
const INACTIVE_COLOR = "var(--mui-palette-grey-400)"

interface DocumentIconProps {
  active?: boolean
  size?: number
  sx?: SxProps<Theme>
}

/**
 * Document icon with 3 bulleted lines -- represents "show all" or "list view"
 */
export function DocumentListIcon({
  active = false,
  size = 36,
  sx,
}: DocumentIconProps) {
  return (
    <Box
      sx={{
        width: size,
        height: size,
        color: active ? ACTIVE_COLOR : INACTIVE_COLOR,
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        transition: "color 0.3s ease", // theme.transition.color equivalent
        ...sx,
      }}
    >
      <svg
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        strokeWidth="1"
        strokeLinecap="round"
        strokeLinejoin="round"
        xmlns="http://www.w3.org/2000/svg"
        aria-hidden="true"
        style={{ width: "100%", height: "100%", marginRight: "-12px" }}
      >
        <rect x="5" y="4" width="14" height="16" rx="2" />
        <circle cx="8" cy="9" r="0.5" fill="currentColor" />
        <path d="M10.5 9h5" />
        <circle cx="8" cy="12" r="0.5" fill="currentColor" />
        <path d="M10.5 12h5" />
        <circle cx="8" cy="15" r="0.5" fill="currentColor" />
        <path d="M10.5 15h5" />
      </svg>
    </Box>
  )
}

/**
 * Document icon with 2 checked lines -- represents "show only chosen" or filtered subset
 */
export function DocumentCheckedIcon({
  active = false,
  size = 36,
  sx,
}: DocumentIconProps) {
  return (
    <Box
      sx={{
        width: size,
        height: size,
        color: active ? ACTIVE_COLOR : INACTIVE_COLOR,
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        transition: "color 0.3s ease", // theme.transition.color equivalent
        ...sx,
      }}
    >
      <svg
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        strokeWidth="1.15"
        strokeLinecap="round"
        strokeLinejoin="round"
        xmlns="http://www.w3.org/2000/svg"
        aria-hidden="true"
        style={{ width: "100%", height: "100%" }}
      >
        <rect x="5" y="4" width="14" height="16" rx="2" />
        <path d="M7 9l1 1 1.5-1.5" strokeWidth="1.3" />
        <path d="M11 9h4.5" />
        <path d="M7 12l1 1 1.5-1.5" strokeWidth="1.3" />
        <path d="M11 12h4.5" />
      </svg>
    </Box>
  )
}

/**
 * Document icon with 3 lines (bold top line) -- represents "show definitions"
 */
export function DocumentExpandedIcon({
  active = false,
  size = 36,
  sx,
}: DocumentIconProps) {
  return (
    <Box
      sx={{
        width: size,
        height: size,
        color: active ? ACTIVE_COLOR : INACTIVE_COLOR,
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        transition: "color 0.3s ease", // theme.transition.color equivalent
        ...sx,
      }}
    >
      <svg
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        strokeWidth="1.15"
        strokeLinecap="round"
        strokeLinejoin="round"
        xmlns="http://www.w3.org/2000/svg"
        aria-hidden="true"
        style={{ width: "100%", height: "100%", marginRight: "-12px" }}
      >
        <rect x="5" y="4" width="14" height="16" rx="2" />
        <path d="M8 8h8" strokeWidth="1.6" />
        <path d="M8 11.5h8M8 14.5h5" />
      </svg>
    </Box>
  )
}

/**
 * Document icon with 1 line (bold top line) -- represents "hide definitions"
 */
export function DocumentCollapsedIcon({
  active = false,
  size = 36,
  sx,
}: DocumentIconProps) {
  return (
    <Box
      sx={{
        width: size,
        height: size,
        color: active ? ACTIVE_COLOR : INACTIVE_COLOR,
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        transition: "color 0.3s ease", // theme.transition.color equivalent
        ...sx,
      }}
    >
      <svg
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        strokeWidth="1.15"
        strokeLinecap="round"
        strokeLinejoin="round"
        xmlns="http://www.w3.org/2000/svg"
        aria-hidden="true"
        style={{ width: "100%", height: "100%" }}
      >
        <rect x="5" y="4" width="14" height="16" rx="2" />
        <path d="M8 8h8" strokeWidth="1.6" />
      </svg>
    </Box>
  )
}

/**
 * CurrentOps icon
 * active=true gives blue fill (ACTIVE_COLOR); active=false gives grey fill (INACTIVE_COLOR).
 * Inner paths are always white.
 * Source: apps/main/public/images/icons/current_ops.svg
 */
export function CurrentOpsIcon({
  active = false,
  size = 36,
  sx,
}: DocumentIconProps) {
  return (
    <Box
      sx={{
        width: size,
        height: size,
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        transition: "color 0.3s ease",
        ...sx,
      }}
    >
      <svg
        viewBox="0 0 120 120"
        xmlns="http://www.w3.org/2000/svg"
        aria-hidden="true"
        style={{ width: "100%", height: "100%" }}
      >
        {/* Background circle */}
        <circle
          cx="60"
          cy="60"
          r="60"
          fill={active ? ACTIVE_COLOR : INACTIVE_COLOR}
        />
        {/* Flame */}
        <path
          fill="white"
          d="M60.9,40.29l.5,1.93c1.45,4.12,3.62,7.95,5.95,11.62,3.44,5.42,7.8,9.47,5.86,16.57-3.2,11.7-19.75,12.58-24.13,1.32-3.15-8.09,2.52-13.1,6.36-19.38.75-1.23,1.49-2.49,2.17-3.75,1.39-2.6,2.74-5.41,3.29-8.31ZM55.68,58.86c.14-.19.3-.3.63-.66.35-.37-.53-.07-.67,0-5.14,2.41-6.12,10.33-2.9,14.66.47.64,1.8,2.03,3.52,2.78.14.06.19-.07.05-.24-.31-.36-.75-.84-1.03-1.26-3.32-4.74-3.15-10.71.4-15.28Z"
        />
        {/* Gear */}
        <path
          fill="white"
          d="M107.39,49.23h-9.42c-.79-2.68-1.85-5.26-3.18-7.69l6.65-6.66c.92-.92.92-2.41,0-3.32l-12.3-12.3c-.92-.92-2.41-.92-3.32,0l-6.65,6.66c-2.44-1.32-5.01-2.39-7.69-3.18v-9.41c0-1.29-1.06-2.35-2.35-2.35h-17.4c-1.29,0-2.35,1.06-2.35,2.35v9.41c-2.68.79-5.26,1.85-7.69,3.18l-6.65-6.66c-.92-.92-2.41-.92-3.32,0l-12.3,12.3c-.92.92-.92,2.41,0,3.32l6.65,6.66c-1.32,2.44-2.39,5.01-3.18,7.69h-9.41c-1.29,0-2.35,1.06-2.35,2.35v17.4c0,1.29,1.06,2.35,2.35,2.35h9.41c.79,2.68,1.85,5.26,3.18,7.69l-6.65,6.66c-.92.92-.92,2.41,0,3.32l12.3,12.3c.92.92,2.41.92,3.32,0l6.65-6.66c2.44,1.32,5.01,2.39,7.69,3.18v9.41c0,1.29,1.05,2.35,2.34,2.35h17.4c1.29,0,2.35-1.06,2.35-2.35v-9.41c2.68-.79,5.26-1.85,7.69-3.18l6.66,6.65c.92.92,2.41.92,3.32,0l12.3-12.3c.92-.92.92-2.41,0-3.32l-6.66-6.65c1.32-2.44,2.39-5.01,3.18-7.69h9.41c1.29,0,2.35-1.05,2.35-2.34v-17.4c0-1.29-1.06-2.35-2.35-2.35ZM60.43,91.94c-17.47,0-31.67-14.2-31.67-31.67s14.22-31.67,31.67-31.67,31.67,14.2,31.67,31.67-14.2,31.67-31.67,31.67Z"
        />
      </svg>
    </Box>
  )
}

/**
 * CurrentOpsMultiple icon - three scaled current_ops instances on one circle
 * Used to indicate "show all baseline variations"
 */
export function CurrentOpsMultipleIcon({
  active = false,
  size = 36,
  sx,
}: DocumentIconProps) {
  return (
    <Box
      sx={{
        width: size,
        height: size,
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        transition: "color 0.3s ease",
        ...sx,
      }}
    >
      <svg
        viewBox="0 0 120 120"
        xmlns="http://www.w3.org/2000/svg"
        aria-hidden="true"
        style={{ width: "100%", height: "100%" }}
      >
        {/* Background circle */}
        <circle
          cx="60"
          cy="60"
          r="60"
          fill={active ? ACTIVE_COLOR : INACTIVE_COLOR}
        />
        {/* Large flame.top-left instance */}
        <path
          fill="white"
          d="M38.86,27.31l.28,1.08c.81,2.3,2.02,4.43,3.31,6.47,1.92,3.02,4.35,5.28,3.26,9.23-1.78,6.52-11,7.01-13.44.74-1.75-4.51,1.4-7.3,3.54-10.8.42-.69.83-1.39,1.21-2.09.77-1.45,1.53-3.01,1.83-4.63ZM35.95,37.66c.08-.11.17-.17.35-.37.19-.21-.3-.04-.37,0-2.86,1.34-3.41,5.76-1.62,8.17.26.36,1,1.13,1.96,1.55.08.03.11-.04.03-.13-.17-.2-.42-.47-.57-.7-1.85-2.64-1.75-5.97.22-8.51Z"
        />
        {/* Large gear.top-left instance */}
        <path
          fill="white"
          d="M64.76,32.29h-5.25c-.44-1.49-1.03-2.93-1.77-4.28l3.7-3.71c.51-.51.51-1.34,0-1.85l-6.85-6.85c-.51-.51-1.34-.51-1.85,0l-3.7,3.71c-1.36-.74-2.79-1.33-4.28-1.77v-5.24c0-.72-.59-1.31-1.31-1.31h-9.69c-.72,0-1.31.59-1.31,1.31v5.24c-1.49.44-2.93,1.03-4.28,1.77l-3.7-3.71c-.51-.51-1.34-.51-1.85,0l-6.85,6.85c-.51.51-.51,1.34,0,1.85l3.7,3.71c-.74,1.36-1.33,2.79-1.77,4.28h-5.24c-.72,0-1.31.59-1.31,1.31v9.69c0,.72.59,1.31,1.31,1.31h5.24c.44,1.49,1.03,2.93,1.77,4.28l-3.7,3.71c-.51.51-.51,1.34,0,1.85l6.85,6.85c.51.51,1.34.51,1.85,0l3.7-3.71c1.36.74,2.79,1.33,4.28,1.77v5.24c0,.72.58,1.31,1.3,1.31h9.69c.72,0,1.31-.59,1.31-1.31v-5.24c1.49-.44,2.93-1.03,4.28-1.77l3.71,3.7c.51.51,1.34.51,1.85,0l6.85-6.85c.51-.51.51-1.34,0-1.85l-3.71-3.7c.74-1.36,1.33-2.79,1.77-4.28h5.24c.72,0,1.31-.58,1.31-1.3v-9.69c0-.72-.59-1.31-1.31-1.31h.01ZM38.6,56.08c-9.73,0-17.64-7.91-17.64-17.64s7.92-17.64,17.64-17.64,17.64,7.91,17.64,17.64-7.91,17.64-17.64,17.64Z"
        />
        {/* Small flame.bottom-left instance */}
        <path
          fill="white"
          d="M51.23,81.96l.19.75c.56,1.6,1.4,3.09,2.31,4.51,1.34,2.1,3.03,3.68,2.27,6.43-1.24,4.54-7.67,4.88-9.36.51-1.22-3.14.98-5.08,2.47-7.52.29-.48.58-.97.84-1.46.54-1.01,1.06-2.1,1.28-3.23ZM49.2,89.17c.05-.07.12-.12.24-.26.14-.14-.21-.03-.26,0-1.99.94-2.38,4.01-1.13,5.69.18.25.7.79,1.37,1.08.05.02.07-.03.02-.09-.12-.14-.29-.33-.4-.49-1.29-1.84-1.22-4.16.16-5.93Z"
        />
        {/* Small gear.bottom-left instance */}
        <path
          fill="white"
          d="M69.27,85.43h-3.66c-.31-1.04-.72-2.04-1.23-2.98l2.58-2.58c.36-.36.36-.94,0-1.29l-4.77-4.77c-.36-.36-.94-.36-1.29,0l-2.58,2.58c-.95-.51-1.94-.93-2.98-1.23v-3.65c0-.5-.41-.91-.91-.91h-6.75c-.5,0-.91.41-.91.91v3.65c-1.04.31-2.04.72-2.98,1.23l-2.58-2.58c-.36-.36-.94-.36-1.29,0l-4.77,4.77c-.36.36-.36.94,0,1.29l2.58,2.58c-.51.95-.93,1.94-1.23,2.98h-3.65c-.5,0-.91.41-.91.91v6.75c0,.5.41.91.91.91h3.65c.31,1.04.72,2.04,1.23,2.98l-2.58,2.58c-.36.36-.36.94,0,1.29l4.77,4.77c.36.36.94.36,1.29,0l2.58-2.58c.95.51,1.94.93,2.98,1.23v3.65c0,.5.41.91.91.91h6.75c.5,0,.91-.41.91-.91v-3.65c1.04-.31,2.04-.72,2.98-1.23l2.58,2.58c.36.36.94.36,1.29,0l4.77-4.77c.36-.36.36-.94,0-1.29l-2.58-2.58c.51-.95.93-1.94,1.23-2.98h3.65c.5,0,.91-.41.91-.91v-6.75c0-.5-.41-.91-.91-.91h0ZM51.04,102.01c-6.78,0-12.29-5.51-12.29-12.29s5.52-12.29,12.29-12.29,12.29,5.51,12.29,12.29-5.51,12.29-12.29,12.29Z"
        />
        {/* Medium flame.right instance */}
        <path
          fill="white"
          d="M89.66,48.69l.28,1c.79,2.12,1.94,4.09,3.18,5.97,1.83,2.78,4.12,4.84,3.18,8.53-1.56,6.09-10.12,6.69-12.49.89-1.7-4.16,1.19-6.81,3.13-10.09.38-.64.75-1.3,1.09-1.96.7-1.36,1.37-2.83,1.63-4.33ZM87.11,58.35c.07-.1.15-.16.32-.35.18-.19-.28-.03-.35,0-2.64,1.29-3.08,5.4-1.38,7.62.25.33.95,1.04,1.85,1.41.07.03.1-.04.02-.12-.16-.18-.4-.43-.54-.64-1.76-2.43-1.72-5.52.08-7.92Z"
        />
        {/* Medium gear.right instance */}
        <path
          fill="white"
          d="M109.6,44.06l-4.46,1.97c-.94-1.1-1.98-2.11-3.12-2.98l1.76-4.55c.24-.63-.07-1.33-.7-1.57l-8.4-3.25c-.63-.24-1.33.07-1.57.7l-1.76,4.55c-1.43-.11-2.87-.08-4.31.1l-1.97-4.46c-.27-.61-.99-.89-1.61-.62l-8.25,3.64c-.61.27-.89.99-.62,1.61l1.97,4.46c-1.1.94-2.11,1.98-2.98,3.12l-4.55-1.76c-.63-.24-1.33.07-1.57.7l-3.25,8.4c-.24.63.07,1.33.7,1.57l4.55,1.76c-.11,1.43-.08,2.87.1,4.31l-4.46,1.97c-.61.27-.89.99-.62,1.61l3.64,8.25c.27.61.99.89,1.61.62l4.46-1.97c.94,1.1,1.98,2.11,3.12,2.98l-1.76,4.55c-.24.63.07,1.33.7,1.57l8.4,3.25c.63.24,1.33-.07,1.57-.7l1.76-4.55c1.43.11,2.87.08,4.31-.1l1.97,4.46c.27.61.99.89,1.6.62l8.25-3.64c.61-.27.89-.99.62-1.61l-1.97-4.46c1.1-.94,2.11-1.98,2.98-3.12l4.55,1.76c.63.24,1.33-.07,1.57-.7l3.25-8.4c.24-.63-.07-1.33-.7-1.57l-4.55-1.76c.11-1.43.08-2.87-.1-4.31l4.46-1.97c.61-.27.89-.99.62-1.6l-3.64-8.25c-.27-.61-.99-.89-1.61-.62h0ZM96.3,74.14c-8.28,3.66-17.98-.1-21.64-8.38s.11-17.99,8.38-21.64,17.98.1,21.64,8.38c3.66,8.28-.1,17.98-8.38,21.64Z"
        />
      </svg>
    </Box>
  )
}

/**
 * Map icon with location pin and geographic features
 */
export function MapIcon({ active = false, size = 44, sx }: DocumentIconProps) {
  return (
    <Box
      sx={{
        width: size,
        height: size,
        color: active ? ACTIVE_COLOR : INACTIVE_COLOR,
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        transition: "color 0.3s ease", // theme.transition.color equivalent
        ...sx,
      }}
    >
      <svg
        viewBox="0 0 24 24"
        fill="currentColor"
        stroke="currentColor"
        strokeWidth="1"
        xmlns="http://www.w3.org/2000/svg"
        aria-hidden="true"
        style={{ width: "100%", height: "100%" }}
      >
        <path
          d="M12 2c-3 0-5.5 2.4-5.5 5.5 0 3.8 5.5 9 5.5 9s5.5-5.2 5.5-9c0-3.1-2.5-5.5-5.5-5.5zm0 7.5c-1 0-1.8-.8-1.8-1.8s.8-1.8 1.8-1.8 1.8.8 1.8 1.8-.8 1.8-1.8 1.8z"
          stroke="none"
        />
        <rect x="3.5" y="12" width="17" height="8" rx="1.5" fill="none" />
        <path
          d="M18 12.5h-1.5c-.02.35-.1.7-.2.95.05 0 .1.01.15.01.3.01.6-.02.9.01.6.07 1.1.45 1.35.95l-.24-1.7c-.02-.16-.16-.27-.33-.27h-.1z"
          opacity="0.7"
          stroke="none"
        />
        <path
          d="M7 15.5c.33-.18.75-.2 1.1-.11.37.07.72.22 1.08.34.36.12.75.22 1.12.17.35-.04.68-.2.92-.45.31-.32.46-.84.2-1.2-.07-.1-.17-.17-.28-.22l-.28.45c-.21.32-.57.52-.95.52s-.75-.2-.95-.52l-.44-.7c-.6-.05-1.2-.21-1.65-.6-.22-.19-.4-.44-.65-.6-.53-.34-1.2-.22-1.82-.08l-.8 6c-.03.2.14.38.34.38h4.42c.05-.54-.19-1.02-.61-1.37-.22-.18-.49-.3-.75-.46-.23-.16-.45-.38-.52-.66-.08-.37.15-.76.49-.95z"
          opacity="0.9"
          stroke="none"
        />
        <path
          d="M16.5 17.5c-.24-.19-.32-.68-.74-.62-.67.09-.11 1-.81 1.29-.22.09-.4.22-.4.49 0 .51.58.73.97.52.21-.11.28-.3.51-.42.37-.2.93.1 1.28-.15.28-.2.32-.65.05-.86-.24-.2-.61-.06-.86-.26z"
          opacity="0.8"
          stroke="none"
        />
      </svg>
    </Box>
  )
}
